FROM openjdk:8
MAINTAINER luiz_segundo
LABEL version="1.0"
LABEL description="Controlador de Pessoas"
ADD target/br.com.eurekaServer-1.0.jar ./
ENTRYPOINT ["java", "-jar", "ControlePessoa-0.0.1-SNAPSHOT.jar"]
EXPOSE 9091